# Folosește Python 3.10 ca imagine de bază
FROM python:3.10

# Setează directorul de lucru în container
WORKDIR /app

# Copiază fișierul test.py în container
COPY test.py .

# Comandă pentru rularea scriptului
CMD ["python", "test.py"]
